[build.environment]
  NODE_VERSION = "18"

[build]
  publish = ".vitepress/dist"
  command = "npm run build"

[build.processing]
  skip_processing = false
[build.processing.html]
  minify = false
[build.processing.css]
  minify = false
[build.processing.js]
  minify = false